config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index' , as:'home'
get 'about' => 'pages#about'
#get '/men/:name' => 'posts#men'
resources :posts do
	resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user , optional: true
	validates :title, presence:true,length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters , if: :devise_controller?

  def configure_permitted_parameters
      	devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:first_name , :last_name , :email , :password , :remember_me)}
      	devise_parameter_sanitizer.permit(:sign_in){ |u| u.permit(:email , :password , :remember_me)}
      	devise_parameter_sanitizer.permit(:account_update){ |u| u.permit(:first_name , :last_name , :email , :password , :current_password , :remember_me)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

#http_basic_authenticate_with name: "omar" , password: "123456" , only: [:destroy]
    

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private def comment_params
       params.require(:comment).permit(:username , :body)
	end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
         @title = 'About Us';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
  # http_basic_authenticate_with name: "omar" , password: "123456" , except: [:index , :show]

   def index
       @posts = Post.all
   end

   def new
      if current_user
        @post = current_user.posts.build
      else
        @post = Post.new
      end
   end

   def show
   	  @post = Post.find(params[:id])
   end

   def create
       #render plain: params[:post].inspect
       if current_user
        @post = current_user.posts.build(post_params)
      else
        @post = Post.new(post_params)
      end
       if(@post.save)
       	  redirect_to @post
       else
          render 'new'
       end
   end

   def edit
   	   @post = Post.find(params[:id])
   end
   def update
   	   @post = Post.find(params[:id]) 
   	   if(@post.update(post_params))
       	  redirect_to @post
       else
          render 'edit'
       end
   end

   def destroy
   	   @post = Post.find(params[:id])
   	   @post.destroy
   	   redirect_to posts_path
   end

   private def post_params
   	   params.require(:post).permit(:title , :body)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

   def titleBody
   	  @post.title + " " + @post.body
   end

end

app/views/comments/_comments.html.erb
<h3>Comment</h3>
<% @post.comments.each do |comment| %>
   <p><strong><%= comment.username %></strong>:<%= comment.body %> 
   	<%= link_to '[X]' , [comment.post , comment] , method: :delete , data:{confirm:'are you sure'} %> 
   </p>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post , @post.comments.build]) do |f| %>
	<p>
		<%= f.label :username %><br>
		<%= f.text_field(:username , {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_field(:body , {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit({:class => 'btb btn-defailt'}) %>
	</p>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">SimpleBlog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
             <%= link_to "Home", home_path %>  
          </li>
        </ul>

        <ul class="navbar-nav mr-auto navbar-right">
          <li class="nav-item">
             <%= link_to "Create Post", new_post_path %>  
          </li>
        </ul>

      </div>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

    </nav>

<div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title %> </h1>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post , url: post_path(@post) , method: :patch do |f| %>
  <% if @post.errors.any? %>
     <% @post.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
     <% end %>
  <% end %>
   <p>
   	<%= f.label :title %><br>
   	<%= f.text_field(:title , {:class => 'form-control'}) %>
   </p>

   <p>
   	<%= f.label :body %><br>
   	<%= f.text_area(:body , {:class => 'form-control'}) %>
   </p>

   <p>
   	<%= f.submit(:class => 'btn btn-primary') %>
   </p>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
   <div class="well">
      <h3> <%= post.title %> </h3>
      <p> <%= post.body %> </p>
      <%= link_to "readMore" , post_path(post), :class =>'btn btn-default' %>
   </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post , url: posts_path do |f| %>
  <% if @post.errors.any? %>
     <% @post.errors.full_messages.each do |msg| %>
     <div class="alert alert-danger"><%= msg %></div>
     <% end %>
  <% end %>
   <p>
   	<%= f.label :title %><br>
   	<%= f.text_field(:title , {:class => 'form-control'}) %>
   </p>

   <p>
   	<%= f.label :body %><br>
   	<%= f.text_area(:body , {:class => 'form-control'}) %>
   </p>

   <p>
   	<%= f.submit(:class => 'btn btn-primary') %>
   </p>

<% end %>

app/views/posts/show.html.erb
<p> body plus title from helper </p>
   	<p> <%= titleBody %> </p>
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<%= link_to "Edit" , edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete" , post_path(@post), method: :delete, 
                                         data: {confirm: 'Are You Sure'} ,
                                         :class => 'btn btn-danger' %>
<hr>

<%= render 'comments/comments' %>
<%= render 'comments/form' %>